# -*- coding: utf-8 -*-
"""
Created on Thu Oct 14 10:28:40 2021

@author: danie
"""


# INITIAL:
#     SOLVE ROOM 2 WITH STANDARD DIRICHLET CONDITION
# STEP1:
#     CALCULATE NEUMANN VALUES IN GAMMA 1 AND GAMMA 3
# STEP2: 
#     SEND NEUMANN VALUES TO PROCESS 1 AND 3 (ROOM 1 AND 3)
# STEP3:
#     RECIEVE NEUMANN CONDITION AND COMPUTE THE 
#     NEUMANN CONDITION PROBLEM IN ROOM 1 AND 3
# STEP4:
#     SEND THE BORDER VALUES TO ROOM 2
# STEP5:
#     RECIEVE DIRICHLET CONDITION AND SOLVE ROOM 2
# STEP6:
#     REPEAT FOR 10 ITERATIONS



